export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
export const ADD_POST_LIKE_REQUEST = 'ADD_LIKE_REQUEST';
export const ADD_POST_LIKE_SUCCESS = 'ADD_LIKE_SUCCESS';
export const ADD_POST_LIKE_ERROR = 'ADD_LIKE_ERROR';
